name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/gh-pages.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Debug - Show Hugo version
        run: hugo version

      - name: Debug - Show Hugo config
        run: |
          echo "=== Hugo config ==="
          hugo config -s docs
          echo "=== Hugo config end ==="

      - name: Debug - Show directory structure before build
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Root directory contents ==="
          ls -la
          echo "=== Docs directory contents ==="
          ls -la docs/
          echo "=== Docs content directory ==="
          ls -la docs/content/
          echo "=== Docs layouts directory ==="
          ls -la docs/layouts/

      - name: Build
        run: |
          echo "=== Starting Hugo build ==="
          hugo -s docs -d docs/public --logLevel debug
          echo "=== Hugo build completed ==="
          echo "=== Checking if docs/public directory exists ==="
          ls -la docs/
          echo "=== Checking if docs/public directory was created ==="
          if [ -d "docs/public" ]; then
            echo "docs/public directory exists"
            ls -la docs/public/
          else
            echo "docs/public directory does not exist"
            echo "=== Checking for other potential output directories ==="
            find . -name "*.html" -type f | head -10
          fi

      - name: Debug - Show build output
        run: |
          echo "=== Docs/public directory contents ==="
          ls -la docs/public/
          echo "=== Docs/public directory size ==="
          du -sh docs/public/
          echo "=== Docs/public directory tree (first 3 levels) ==="
          find docs/public/ -type f | head -20

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/public
          publish_branch: gh-pages 